### ISSUE TITLE
16-bit per channel PNG to Uint16Array?

### ISSUE THREAD

**Issue by mortac8** [photopea/UPNG.js#54]
Is it possible to get values from a 16-bit per channel PNG as a Uint16Array?

**Comment by photopea** [comment]
Hi, sure! The object returned by UPNG.decode() has a property "data" with 16-bit raster data of the image.

If you want to use the same ArrayBuffer, you need to swap pairs of bytes from big endian to a little endian.

See here: https://github.com/photopea/UPNG.js/issues/30

**Comment by mortac8** [comment]
I read through the comments on issue #30 but I have a RGBA image I need help with.  Can you advise?  Sorry to bother you again.

http://www.schaik.com/pngsuite/basn6a16.png
![upngHelp](https://user-images.githubusercontent.com/1685158/91781655-6e992580-ebc0-11ea-8e0c-9b98a43423ed.png)

**Comment by photopea** [comment]
BTW. the domain http://www.schaik.com/ does not work for me :(

I opened the basn6a16.png in Photopea.com (which uses UPNG.js) and it seems to work correctly (as your example on the right).

If you need to open any PNG image as a 8-channel RGBA image, use UPNG.toRGBA8(....).

The images in your screenshot look different. I think it could be because of additional multiplying or dividing the RGB values by alpha value.

**Comment by mortac8** [comment]
Your comment was very helpful.  It turns out I had to set {premultipliedAlpha: false} on my webgl2 context which fixed the visual differences.
